apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  DB_NAME: {{ .Values.env.DB_NAME }}
  AWS_S3_BUCKET_NAME: {{ .Values.env.AWS_S3_BUCKET_NAME }}
  APP_ENV: {{ .Values.env.APP_ENV }}
