apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_HOST: {{ .Values.secretEnv.DB_HOST | b64enc }}
  DB_USER: {{ .Values.secretEnv.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.secretEnv.DB_PASSWORD | b64enc }}
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.secretEnv.AWS_ACCESS_KEY_ID | b64enc}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secretEnv.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_SESSION_TOKEN: {{ .Values.secretEnv.AWS_SESSION_TOKEN | b64enc }}
